# Generated by Django 4.2 on 2023-04-13 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbclone', '0003_surveyfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SurveyFile',
            new_name='AvatarChange',
        ),
    ]
