# Generated by Django 4.2 on 2023-04-13 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbclone', '0004_rename_surveyfile_avatarchange'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvatarChange',
        ),
    ]
