# Generated by Django 4.2 on 2023-04-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbclone', '0011_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
