# Generated by Django 4.2 on 2023-04-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbclone', '0012_customuser_about_customuser_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examplefield', models.CharField(max_length=100)),
            ],
        ),
    ]
