# Generated by Django 4.2 on 2023-04-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbclone', '0013_examplemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
    ]
