# Generated by Django 4.2 on 2023-04-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbclone', '0016_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
