# Generated by Django 4.2 on 2023-05-12 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbclone', '0019_alter_customuser_birth_date_like_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='about',
        ),
    ]
